version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: civic_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d
    networks:
      - civic-network

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - civic-network

  # Backend API Server
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:password@postgres:5432/civic_tracker
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-jwt-secret-key
      TWILIO_ACCOUNT_SID: your-twilio-sid
      TWILIO_AUTH_TOKEN: your-twilio-token
      AWS_ACCESS_KEY_ID: your-aws-key
      AWS_SECRET_ACCESS_KEY: your-aws-secret
      AWS_S3_BUCKET: civic-tracker-media
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - postgres
      - redis
    networks:
      - civic-network

  # Admin Portal (Next.js)
  admin-portal:
    build:
      context: ./admin-portal
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
      NEXT_PUBLIC_WS_URL: ws://localhost:3001
    volumes:
      - ./admin-portal:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - civic-network

  # Mobile App Metro Bundler (for development)
  mobile-dev:
    build:
      context: ./mobile-app
      dockerfile: Dockerfile.dev
    ports:
      - "19000:19000"  # Expo DevTools
      - "19001:19001"  # Expo Metro Bundler
      - "19002:19002"  # Expo Tunnel
    environment:
      EXPO_DEVTOOLS_LISTEN_ADDRESS: 0.0.0.0
      REACT_NATIVE_PACKAGER_HOSTNAME: 192.168.1.100  # Replace with your local IP
    volumes:
      - ./mobile-app:/app
      - /app/node_modules
    networks:
      - civic-network

volumes:
  postgres_data:
  redis_data:

networks:
  civic-network:
    driver: bridge
